### ISSUE TITLE
[1.6-1.19.2] Pattern Encoding causes a client crash

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [62832/Fullblock-Energistics#5]
**Minecraft**: 1.19.2
**Fabric API**: 0.77.0+1.19.2
**Fabric Loader**: 0.15.7
**AE2**: 12.9.9
**Fullblock Energistics**: 1.6-1.19.2
**MEGA Cells**: 2.0.4-1.19.2 (unknown if this mod is related to crash, but let it be here)

When attempting to take an empty or encoded pattern disk from Fullblock Pattern Encoding Terminals you can get crashed due to an attempt of getting Level instance in the clientside event, while Level is unreachable at this point and causes the crash.

**Logs**:
```
net.minecraft.util.crash.CrashException: mouseClicked event handler
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1205) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class gripe._90.fulleng.block.entity.terminal.PatternEncodingTerminalBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.world.World getLevel()' of interface appeng.helpers.IPatternTerminalLogicHost.
	at appeng.parts.encoding.PatternEncodingLogic.isClientSide(PatternEncodingLogic.java:90) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.eventsEnabled(AppEngInternalInventory.java:148) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.onContentsChanged(AppEngInternalInventory.java:139) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.notifyContentsChanged(AppEngInternalInventory.java:93) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.setItemDirect(AppEngInternalInventory.java:84) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.extractItem(AppEngInternalInventory.java:119) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.menu.slot.AppEngSlot.takeStack(AppEngSlot.java:180) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at net.minecraft.screen.slot.Slot.tryTakeStackRange(Slot.java:111) ~[client-intermediary.jar:?]
	at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler.java:420) ~[client-intermediary.jar:?]
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler.java:293) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager.java:450) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen.java:569) ~[client-intermediary.jar:?]
	at appeng.client.gui.AEBaseScreen.onMouseClick(AEBaseScreen.java:650) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.client.gui.me.common.MEStorageScreen.onMouseClick(MEStorageScreen.java:498) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseClicked(HandledScreen.java:361) ~[client-intermediary.jar:?]
	at appeng.client.gui.AEBaseScreen.mouseClicked(AEBaseScreen.java:529) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.client.gui.me.common.MEStorageScreen.mouseClicked(MEStorageScreen.java:468) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.client.gui.me.items.PatternEncodingTermScreen.mouseClicked(PatternEncodingTermScreen.java:117) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:489) ~[client-intermediary.jar:?]
	... 24 more
```

Let me know if you need more info!

**Comment by 62832** [comment]
Thanks for the report. Will investigate right away.

EDIT: Hm, odd. This should have been fixed already.

**Comment by DenisMasterHerobrine** [comment]
Just rechecked the CurseForge release, seems fix is not being uploaded to it? Rechecked everything and still getting the crash.

EDIT: Yes, definitely it is missing on CF. The latest release is from September, while the fix is done in December, maybe it needs rebuilding and reuploading it?

**Comment by 62832** [comment]
Oh, yeah, I forgot to make a release altogether since then. Sorry about that! Should be coming shortly.

**Comment by 62832** [comment]
A release should be out for 1.19.2 in a couple of minutes from now. Would you let me know if that fixes it once you get hold of it?

**Comment by DenisMasterHerobrine** [comment]
Sure, let me check it in my modpack.

**Comment by DenisMasterHerobrine** [comment]
Here's the another crash using the 1.7 version, clean instance. Simply opening the terminal now just crashes the game, even not opening as in 1.6.

Loaded mods:
```
[00:19:40] [main/INFO]: Loading 66 mods:
	- ae2 12.9.9
	   |-- noindium 1.1.0+1.19
	   \-- team_reborn_energy 2.0.0-beta1
	- architectury 6.5.85
	- cloth-config 8.3.115
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.77.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.1.0+ee641e7390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.25+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.28+df3654b390
	   |-- fabric-rendering-v1 1.13.0+526f2c6790
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- fulleng 1.7-1.19.2
	- java 17
	- minecraft 1.19.2
	- modmenu 4.2.0-beta.2
	- roughlyenoughitems 9.1.682
	   \-- error_notifier 1.0.9
	- travellersbootsreloaded 2.0.1-fabric
```

```
[00:20:40] [Server thread/INFO]: Assigning ME player id 0 to Minecraft profile ca8fd19c-ab82-46d8-b5cb-3589b421993e (_DMH_)
[00:20:40] [Render thread/ERROR]: Unreported exception thrown!
java.lang.AbstractMethodError: Receiver class gripe._90.fulleng.block.entity.terminal.PatternEncodingTerminalBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_1937 getLevel()' of interface appeng.helpers.IPatternTerminalLogicHost.
	at appeng.parts.encoding.PatternEncodingLogic.isClientSide(PatternEncodingLogic.java:90) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.eventsEnabled(AppEngInternalInventory.java:148) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.onContentsChanged(AppEngInternalInventory.java:139) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.notifyContentsChanged(AppEngInternalInventory.java:93) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.util.inv.AppEngInternalInventory.setItemDirect(AppEngInternalInventory.java:84) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at appeng.menu.slot.AppEngSlot.method_44206(AppEngSlot.java:133) ~[appliedenergistics2-fabric-12.9.9.jar:?]
	at net.minecraft.class_1703.method_7610(class_1703.java:592) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11153(class_634.java:1112) ~[client-intermediary.jar:?]
	at net.minecraft.class_2649.method_11439(class_2649.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_2649.method_11054(class_2649.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```

**Comment by 62832** [comment]
This seriously makes no sense. Let me take a closer look.

EDIT: Right, I see. The problem would definitely be because of the fact that the method in question also exists by that same name in Minecraft's own `BlockEntity` class, but this gets remapped to have another name in an actual game outside of a development environment. I'm gonna have to make a work-around for this.

**Comment by 62832** [comment]
Pushed another fix and deployed some new builds. Keep an eye out for a version 1.7.1 build and try that out, I've tested it on my end and now there should no longer be any issue.

**Comment by 62832** [comment]
@DenisMasterHerobrine Build is out. Is it working for you now?

**Comment by DenisMasterHerobrine** [comment]
Yes, version 1.7.1 works for me just fine, will test it in the modpack with other mods a bit later, but I think that this should be fixed in modpack too, because this was reproducible in a clean instance with just AE2 and Fullblock Energistics. Thanks for the quick fix!

**Comment by 62832** [comment]
While you're at it, out of curiosity, do you suppose you could give the latest 1.20.4 version a try as well to see if this bug is present again or if it's gone for good?

**Comment by DenisMasterHerobrine** [comment]
Sorry for the delay, tested it in my modpack and in 1.20.4 versions, it puts into the slot now correctly, but the recipe cannot be encoded to it, seems that there is an issue with instancing the pattern outside the pattern encoding terminal context?

**Comment by 62832** [comment]
Interesting. I'll investigate this tomorrow.

**Comment by 62832** [comment]
@DenisMasterHerobrine I'm unable to currently reproduce this on my end in development and I've not currently got a production environment set up for NeoForge 1.20.4. Do you happen to have a proper log for what you mentioned earlier?

**Comment by DenisMasterHerobrine** [comment]
> @DenisMasterHerobrine I'm unable to currently reproduce this on my end in development and I've not currently got a production environment set up for NeoForge 1.20.4. Do you happen to have a proper log for what you mentioned earlier?

I can try right now to reproduce the issue in my modpack in 1.19.2 just to check it out and find out the logs, the 1.20.4 version will test a bit later.

**Comment by DenisMasterHerobrine** [comment]
Sorry for the delay again, had not a lot of time and I totally forgot about that this night, fixing this up:

1.19.2:
Clean instance with just AE2 12.9.9 and Fullblock Energistics 1.7.1 and REI 9.1.682: everything now seems fine, except REI issue (see below)
In my modpack instance, the client and server have both AE2 12.9.9 and Fullblock Energistics 1.7.1: If I try to sort the inventory using Inventory Profiles Next, the pattern dissappears and voids itself. If I try to get any item from REI in Cheat Mode, the item gets into inventory, but the GUI closes immediately. Also this happens every time I try to delete an item.

After doing some tests on the modpack/server backend, made sure that the hashsums of both client/server jars are identical it started working as expected, the patterns are encoding properly, but the REI and sorting issue are still there.

When retrieving an item from REI I get this (and only this) error in the logs:
```
Error executing task on Client
java.lang.NullPointerException: null
```

1.20.4:
Clean instance with AE2 17.13.0-neoforge, Fullblock Energistics 2.0-beta, seems that there is no issues, but there is still an issue when attempting to lookup a recipe/take the item from REI, the GUI closes itself immediately and kicks me outside the block's interface.  Also I need to mention, that there is literally no logs about this behaviour in my logs for 1.20.4 NeoForge test environment.
```
[19May2024 14:15:15.909] [Netty Local Client IO #0/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Gave [Iron Ingot] x1 to _DMH_.
[19May2024 14:15:16.001] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: _DMH_ has made the advancement [Acquire Hardware]
[19May2024 14:15:16.010] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] _DMH_ has made the advancement [Acquire Hardware]
[19May2024 14:15:16.010] [Render thread/INFO] [net.minecraft.advancements.AdvancementTree/]: Loaded 50 advancements
[19May2024 14:15:18.446] [Netty Local Client IO #0/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Gave [Iron Ingot] x64 to _DMH_.
```

![image](https://github.com/62832/Fullblock-Energistics/assets/27882185/88352e49-c08b-4a5e-beb4-b2ce8004b954)
(Also I'm not sure about the white frame intended behaviour in 1.20.4 build, it seems to appear every time the pattern is encoded, but it clears every time I click anywhere in the GUI and not taking the pattern. Seems it should appear for some time and dissappear after some time or appear when the pattern is not taken and ready after encoding? Let me know if this is an intended behaviour, thanks)

I had a somewhat bleeding-edge pack for 1.20.4 somewhere where I tested Fullblock Energistics and had the same issues with 1.19.2 versions with correctly putting a pattern, but no success of encoding it, while the AE2's Pattern Terminal was working as intended, but seems I lost the pack or moved to a folder, which I forgot where is located. Sorry, seems I cannot test it in modpack environment in 1.20.4.

Overall, this issue seems to be fixed, but there are still some random shenanigans happening in the modpacks related to mod incompatibilities or whatever it sometimes does not allow to process the pattern as intended. However, clean instances show that it is now not crashing and processing the pattern as expected.

Let me know, if you need to test out a new version or give some other logs.

**Comment by 62832** [comment]
Does any of this behaviour you mention with REI happen with the *regular* Pattern Encoding Terminal?

**Comment by DenisMasterHerobrine** [comment]
> Does any of this behaviour you mention with REI happen with the _regular_ Pattern Encoding Terminal?

As far as I tested just right now in my modpack for 1.19.2: seems to be no, regular one working just fine.
In 1.20.4 clean instance seems to be reproducible in the regular Pattern Encoding Terminal too.

I'm not sure, on which end the REI related issue occurs, but for me it happens in the 1.20.4 build **only**.

**Comment by 62832** [comment]
Having done further testing on 1.19.2, it seems like the menu-closing bug with REI is actually an upstream AE2 bug that happens on any menu associated with a *block entity* rather than a *part*. I've been able to reproduce it by granting myself an item through REI's cheat mode when looking at the menu for an ME Drive.

I have not yet tested the pattern voiding problem with Inventory Profiles Next. Does that also happen with the AE2 terminal part or no?
